id = "mace"
name = "Mace"
version = "0.0.1"
schema_version = 1
authors = ["Shelton Louis <louisshelton0@gmail.com>"]
description = "This is the official Mace extension for Zed."
repository = "https://github.com/louiss0/zed-extension-mace"

[grammars.mace]
repository = "https://github.com/louiss0/tree-sitter-mace"
rev = "ccce2a9f998a3f131fae66eb4d956b66a8aaea28"

[language_servers.mace]
name = "Mace LSP"
languages = ["Mace"]
