id = "mace"
name = "Mace"
version = "0.0.1"
schema_version = 1
authors = ["Shelton Louis <louisshelton0@gmail.com>"]
description = "This is the official Mace extension for Zed."
repository = "https://github.com/louiss0/zed-extension-mace"

[grammars.mace]
repository = "https://github.com/louiss0/tree-sitter-mace"
rev = "186e3baf373a43b3ab4b7694e709f79ad0d70050"

[language_servers.mace]
name = "Mace LSP"
languages = ["Mace"]
